# Generated by Django 5.2.17 on 2026-09-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=200)),
                ('date_range', models.CharField(help_text='e.g. 2020 — 2024', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Backend Engineer', max_length=150)),
                ('bio_paragraph_1', models.TextField()),
                ('bio_paragraph_2', models.TextField(blank=True)),
                ('bio_paragraph_3', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
